import { useRef } from 'react';
import { Copy, Printer } from 'lucide-react';
import type { AppState } from '../types';
import { Card } from './ui/Card';

const TASTE_LABELS: Record<string, string> = {
  sweet: 'Sweet',
  salty: 'Salty',
  sour: 'Sour',
  bitter: 'Bitter',
  umami: 'Umami',
};

interface RecipeCardProps {
  state: AppState;
  showToast: (msg: string) => void;
}

function avg(scores: Record<string, number>): number {
  const vals = Object.values(scores);
  return Math.round((vals.reduce((s, v) => s + v, 0) / vals.length) * 10) / 10;
}

export function RecipeCard({ state, showToast }: RecipeCardProps) {
  const totalWeight = state.ingredients.reduce((s, i) => s + i.amount, 0);
  const latestRound = state.tastingHistory[state.tastingHistory.length - 1];
  const cardRef = useRef<HTMLDivElement>(null);

  const flavorLines = (Object.entries(state.flavor) as [string, number][])
    .map(([k, v]) => `${TASTE_LABELS[k]}: ${v}/10`)
    .join('  ·  ');

  const ingredientLines = state.ingredients
    .map((i) => {
      const pct = totalWeight > 0 ? Math.round((i.amount / totalWeight) * 100) : 0;
      return `  ${i.name.padEnd(28)} ${String(i.amount).padStart(5)}g  (${pct}%)  [${i.role}]`;
    })
    .join('\n');

  const tastingLine = latestRound
    ? `Round ${latestRound.round} — Avg ${avg(latestRound.scores)}/5 (${latestRound.date})`
    : 'No tasting data yet';

  const phasesDone = Object.values(state.phases).filter((p) => p === 'done').length;

  const text = `
SAUCE LAB — RECIPE CARD
════════════════════════════════════════════════════════════

NAME:    ${state.projectName || 'Untitled'}
STYLE:   ${state.sauceStyle || '—'}
TEXTURE: ${state.targetTexture || '—'}
DATE:    ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

────────────────────────────────────────────────────────────
FLAVOR PROFILE
────────────────────────────────────────────────────────────
${flavorLines}

────────────────────────────────────────────────────────────
INGREDIENTS  (Batch: ${state.batchSize}g)
────────────────────────────────────────────────────────────
${ingredientLines}

Total: ${totalWeight}g

────────────────────────────────────────────────────────────
TEXTURE METHOD
────────────────────────────────────────────────────────────
${state.texture.mechanism}${state.texture.mechanism === 'Reduction' ? ` — ${state.texture.reductionPercent}% reduction` : ''}${state.texture.mechanism === 'Starch' ? ` — ${state.texture.starchType}` : ''}

────────────────────────────────────────────────────────────
SENSORY DATA
────────────────────────────────────────────────────────────
${tastingLine}
Iterations: ${state.tastingHistory.length}

────────────────────────────────────────────────────────────
R&D STATUS
────────────────────────────────────────────────────────────
Phases complete: ${phasesDone}/5

────────────────────────────────────────────────────────────
DEVELOPMENT NOTES
────────────────────────────────────────────────────────────
${state.developmentNotes || 'None'}

════════════════════════════════════════════════════════════
Generated by Sauce Lab
`.trim();

  function copyToClipboard() {
    navigator.clipboard.writeText(text).then(() => showToast('Copied to clipboard!'));
  }

  function printCard() {
    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(`<html><head><title>${state.projectName || 'Recipe Card'}</title>
      <style>body{font-family:monospace;white-space:pre;padding:32px;font-size:13px;line-height:1.6;}</style>
      </head><body>${text.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</body></html>`);
    w.document.close();
    w.print();
  }

  return (
    <div className="space-y-5">
      <div className="flex gap-2">
        <button
          onClick={copyToClipboard}
          className="flex items-center gap-2 px-4 py-2 rounded-lg border border-gray-200 dark:border-gray-700 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-900 transition-colors"
        >
          <Copy size={15} />
          Copy to clipboard
        </button>
        <button
          onClick={printCard}
          className="flex items-center gap-2 px-4 py-2 rounded-lg bg-gray-900 dark:bg-gray-100 text-white dark:text-gray-900 text-sm font-medium hover:bg-gray-700 dark:hover:bg-gray-300 transition-colors"
        >
          <Printer size={15} />
          Print / Save PDF
        </button>
      </div>

      <Card>
        <div ref={cardRef} className="font-mono text-xs leading-relaxed whitespace-pre text-gray-800 dark:text-gray-200 overflow-x-auto">
          {text}
        </div>
      </Card>
    </div>
  );
}
